### ISSUE TITLE
About FPN

### ISSUE THREAD

**Issue by rxqy** [yingxingde/FasterRCNN-pytorch#2]
Hi, have you tested on fpn yet?
tried it with the following command,
`python train.py --net='fpn101' --tag=fpn101 --iters=80000 --cfg='./experiments/cfgs/fpn101.yml' --weight='./data/pretrained_model/resnet101_caffe.pth'`
 but an error occurred.
`line 17, in generate_anchors_global
    ratios=np.array(anchor_ratios), scales=np.array([anchor_scales[index]]))
IndexError: list index out of range
`
It seems like that in the generate_anchor function, although feat_strides were updated to (4, 8, 16, 32, 64), but the anchors were still the same, ie, 8 16 32 .

Also, there seems to be 2 typo in fpn101.yml,
EXP_DIR should be fpn101, SNAPSHOT_PREFIX should be fpn101 I guess?

**Comment by yingxingde** [comment]
what is your python version? my experiment environment is python2.7.  You may debug to check what happened? Like >print(anchor_ratios)?

**Comment by rxqy** [comment]
ehh I can run your code with resnet101, but when I switched to fpn101, something went wrong.
I'm using python2 and pytorch 0.3.1. Am I training in the wrong way? like use a wrong xml file..
And the latest error says:

> File "/home/FasterRCNN-pytorch/lib/rpn/fpn/generate_anchors_global.py", line 23, in generate_anchors_global
    ratios=np.array(anchor_ratios), scales=np.array([anchor_scales[index]]))
IndexError: list index out of range

So I edited the lib/rpn/fpn/generate_anchors_gloabal.py to

```
def generate_anchors_global(feat_strides, heights, widths, anchor_scales=(8,16,32), anchor_ratios=(0.5,1,2)):
  assert len(feat_strides) == len(heights)
  assert len(heights) == len(widths)
  anchors_list = list()
  print('feat_strides',feat_strides)
  print('anchor_scales', anchor_scales)
  print('anchor_ratios', anchor_ratios)
  print('len feat_strides',len(feat_strides))
```

And this is the output:

> interval 50  
step 0  
feat_strides (4, 8, 16, 32, 64)  
anchor_scales [8, 16, 32]  
anchor_ratios [0.5, 1, 2]  
len feat_strides 5  


So I think the problem is that in FPN, we need 5 feature pyramids together to produce the output, and we have 5 feat_strides, but only 3 anchor_scales. So it would give the list index out of range error.

**Comment by rxqy** [comment]
I added another print in file network_fpn,
```
  def _generate_anchors(self, rpn_cls_score_list):
    # anchors [A*K, 4]
    heights = [rpn_cls_score.size()[-2] for rpn_cls_score in rpn_cls_score_list]
    widths = [rpn_cls_score.size()[-1] for rpn_cls_score in rpn_cls_score_list]
    
    print('---------------------------------------------')
    print(self._network._anchor_scales)

    anchors, num_anchors = generate_anchors_global(
      feat_strides=self._network._feat_stride,
      heights=heights,
      widths=widths,
      anchor_scales=self._network._anchor_scales,
      anchor_ratios=self._network._anchor_ratios
    )
```

but the anchor scales here is just 8,16,32
maybe I chose the wrong yml file?
I think (if my calculation is right), the anchor scales here , at 5 different feature maps, should all be 16?

**Comment by rxqy** [comment]
Fixed. Problem is with easydict, installed from conda. Version is 1.4, too old.
Reinstalled with pip, got a newer version of 1.7.
