### ISSUE TITLE
where is _roi_pooling?

### ISSUE THREAD

**Issue by Lvqin001** [yingxingde/FasterRCNN-pytorch#4]
Excuse me，in lib/roi_pooling/_ext/roi_pooling/__init__.py   from ._roi_pooling import lib as _lib, ffi as _ffi .but there don't have module  named _roi_pooling. did you miss the upload?

**Comment by yingxingde** [comment]
I think you may have not compiled the code.  You should bash make.sh in ./lib first.
[detail](https://github.com/yingxingde/FasterRCNN-pytorch/blob/8ea2f9899bffeb8866dc53cd00d4812513588160/lib/make.sh#L5)

**Comment by Lvqin001** [comment]
> I think you may have not compiled the code. You should bash make.sh in ./lib first.
> [detail](https://github.com/yingxingde/FasterRCNN-pytorch/blob/8ea2f9899bffeb8866dc53cd00d4812513588160/lib/make.sh#L5)

yes, thanks for your answer.
